version: "3.9"
services:
  app:
    build: .
    container_name: sensi_app
    restart: unless-stopped
    volumes:
      - uploads_data:/app/static/uploads
      - db_data:/app/instance
    environment:
      SECRET_KEY: change-this-in-production
    networks:
      - internal
    expose:
      - "3000"

  waf:
    image: owasp/modsecurity-crs:nginx
    container_name: sensi_waf
    restart: unless-stopped
    ports:
      - "80:8080"
    environment:
      BACKEND: "http://app:3000"
      PARANOIA: "2"
    depends_on:
      - app
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  uploads_data:
  db_data:
